# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon Piercy
email: brandon.piercy@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
Brandon Piercy's Homepage: Advanced Materials Synthesis
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bpiercy.com" # the base hostname & protocol for your site
github_username:  bpiercy

# Color settings
color:
  primary-dark: '#000000'
  secondary-dark: '#25172e'
  primary-light: '#f8e9fc'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social settings
social:
  - title: linkedin
    url: http://www.linkedin.com/in/brandonpiercy



# Build settings
markdown: kramdown
permalink: pretty