url: https://www.brandonpiercy.com
baseurl: 

# Site settings
title: Brandon Piercy
email: Use the Contact Form!
description: "Brandon D Piercy, Materials Scientist."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: fff
  primary-text: 111
  secondary-bg: ddd
  secondary-text: 555

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:


# Build settings
markdown: kramdown
permalink: pretty